sudo: false

os:
  - linux

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

env:
  matrix:
    - TASK=lint
    - TASK=test
    - TASK=coverage

script:
    - make -f Makefile $TASK
