---
name: justbytes CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # MANDATORY CHECKS THAT USE TOX
  tox-checks:
    strategy:
      matrix:
        task: [lint, test, coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Install dependencies
        run: |
          pip3 install tox==3.19.0
      - name: Run test
        run: make -f Makefile ${{ matrix.task }}

  # FORMAT
  fmt:
    env:
      TASK: fmt-travis
      PYTHON: 3.9.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}
      - name: Install dependencies
        run: |
          pip3 install black==20.8b1
          pip3 install isort==5.6.4
      - name: Run test
        run: make -f Makefile $TASK

  # VERIFICATION OF TEST INFRASTRUCTURE
  yamllint:
    env:
      TASK: yamllint
      PYTHON: 3.9.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}
      - name: Install dependencies
        run: pip3 install yamllint==1.26.0
      - name: Run yamllint
        run: make -f Makefile $TASK
