---
name: justbytes CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # MANDATORY CHECKS THAT USE TOX
  tox-checks:
    strategy:
      matrix:
        task: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          pip3 install tox==3.24.4
      - name: Run test
        run: make -f Makefile ${{ matrix.task }}

  development_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: pylint python3-hypothesis python3-justbases
            task: PYTHONPATH=./src make -f Makefile lint
          - dependencies: >
              pylint
              python3-coverage
              python3-hypothesis
              python3-justbases
            task: PYTHONPATH=./src make -f Makefile coverage
    runs-on: ubuntu-latest
    container: fedora:36  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
