---
name: justbytes weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 3 * * 3
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: pylint python3-hypothesis python3-justbases
            task: PYTHONPATH=./src make -f Makefile lint
    runs-on: ubuntu-latest
    container: fedora:36  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
